# require the branch name to be master (note for PRs this is the base branch name)
if: branch = master

language: python

env:
  global:
  - 'MIJNVAR=$EENVAR'

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.82.0/hugo_0.82.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo --themesDir themes


after_success:
    - cat /tmp/oef.txt
    - echo "hallo daar"
    - echo "${EENVAR}"
    - echo "${MIJNVAR}"
#   - scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no README.md babycarryworkout.com@ssh.babycarryworkout.com:/www
    - rsync -Pav -e "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" public/ babycarryworkout.com@ssh.babycarryworkout.com:/www
    - echo "stoppen maar"
